apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.gogs.type }}
  selector:
    app: gogs
  ports:
  - name: ssh
    port: 2222
    targetPort: 22
    protocol: TCP
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
    {{- if (and (or (eq .Values.service.gogs.type "NodePort")) (not (empty .Values.service.gogs.nodePort))) }}
    nodePort: {{ .Values.service.gogs.nodePort }}
    {{- else if eq .Values.service.gogs.type "ClusterIP" }}
    nodePort: null
    {{- end }}